; Automatically converted to only require STRIPS and negative preconditions

(define (problem parking)
  (:domain parking)
  (:objects car_00 car_01 car_02 car_03 car_04 car_05 car_06 car_07 car_08 car_09 car_10 car_11 car_12 car_13 car_14 car_15 curb_0 curb_1 curb_2 curb_3 curb_4 curb_5 curb_6 curb_7 curb_8)
  (:init
    (at-curb car_10)
    (at-curb-num car_10 curb_0)
    (behind-car car_06 car_10)
    (car-clear car_06)
    (at-curb car_03)
    (at-curb-num car_03 curb_1)
    (behind-car car_15 car_03)
    (car-clear car_15)
    (at-curb car_01)
    (at-curb-num car_01 curb_2)
    (behind-car car_05 car_01)
    (car-clear car_05)
    (at-curb car_08)
    (at-curb-num car_08 curb_3)
    (behind-car car_14 car_08)
    (car-clear car_14)
    (at-curb car_07)
    (at-curb-num car_07 curb_4)
    (behind-car car_09 car_07)
    (car-clear car_09)
    (at-curb car_11)
    (at-curb-num car_11 curb_5)
    (behind-car car_13 car_11)
    (car-clear car_13)
    (at-curb car_04)
    (at-curb-num car_04 curb_6)
    (behind-car car_02 car_04)
    (car-clear car_02)
    (at-curb car_12)
    (at-curb-num car_12 curb_7)
    (car-clear car_12)
    (at-curb car_00)
    (at-curb-num car_00 curb_8)
    (car-clear car_00)
    (car car_00)
    (car car_01)
    (car car_02)
    (car car_03)
    (car car_04)
    (car car_05)
    (car car_06)
    (car car_07)
    (car car_08)
    (car car_09)
    (car car_10)
    (car car_11)
    (car car_12)
    (car car_13)
    (car car_14)
    (car car_15)
    (curb curb_0)
    (curb curb_1)
    (curb curb_2)
    (curb curb_3)
    (curb curb_4)
    (curb curb_5)
    (curb curb_6)
    (curb curb_7)
    (curb curb_8)
  )
  (:goal
    (and
      (at-curb-num car_00 curb_0)
    )
  )
)
