; Summary of the generated problem:
; Dirt: 0
; Robot [Start, Distance]: Edges
; * rob_0 [2, 2]: (0, 6) (0, 7) (1, 3) (1, 4) (1, 5) (2, 4) (2, 7) (3, 6) (3, 4) (5, 6) (5, 7)

(define (problem robot-vacuum)
  (:domain robot-vacuum)
  (:objects rob_0 loc_0 loc_1 loc_2 loc_3 loc_4 loc_5 loc_6 loc_7)
  (:init
    (dirty loc_0)
    (at rob_0 loc_2)
    (adjacent rob_0 loc_0 loc_6)
    (adjacent rob_0 loc_6 loc_0)
    (adjacent rob_0 loc_0 loc_7)
    (adjacent rob_0 loc_7 loc_0)
    (adjacent rob_0 loc_1 loc_3)
    (adjacent rob_0 loc_3 loc_1)
    (adjacent rob_0 loc_1 loc_4)
    (adjacent rob_0 loc_4 loc_1)
    (adjacent rob_0 loc_1 loc_5)
    (adjacent rob_0 loc_5 loc_1)
    (adjacent rob_0 loc_2 loc_4)
    (adjacent rob_0 loc_4 loc_2)
    (adjacent rob_0 loc_2 loc_7)
    (adjacent rob_0 loc_7 loc_2)
    (adjacent rob_0 loc_3 loc_6)
    (adjacent rob_0 loc_6 loc_3)
    (adjacent rob_0 loc_3 loc_4)
    (adjacent rob_0 loc_4 loc_3)
    (adjacent rob_0 loc_5 loc_6)
    (adjacent rob_0 loc_6 loc_5)
    (adjacent rob_0 loc_5 loc_7)
    (adjacent rob_0 loc_7 loc_5)
  )
  (:goal (and (not (dirty loc_0))))
)
