aggregation: max
batch_size: 64
gradient_accumulation: 1
gradient_clip: 0.1
hidden_size: 64
iterations: 30
l1_factor: 0.0
learning_rate: 0.0002
loss: selfsupervised_suboptimal
loss_constants: null
max_samples: null
max_samples_per_file: 1000
patience: 50
predicates:
- !!python/tuple
  - adjacent
  - 2
- !!python/tuple
  - unblocked
  - 1
- !!python/tuple
  - cell
  - 1
- !!python/tuple
  - picked
  - 1
- !!python/tuple
  - at
  - 1
- !!python/tuple
  - reward
  - 1
- !!python/tuple
  - adjacent_goal
  - 2
- !!python/tuple
  - unblocked_goal
  - 1
- !!python/tuple
  - cell_goal
  - 1
- !!python/tuple
  - picked_goal
  - 1
- !!python/tuple
  - at_goal
  - 1
- !!python/tuple
  - reward_goal
  - 1
suboptimal_factor: 2.0
weight_decay: 0.0
