aggregation: max
batch_size: 128
gradient_accumulation: 1
gradient_clip: 0.1
hidden_size: 64
iterations: 30
l1_factor: 0.0
learning_rate: 0.0002
loss: selfsupervised_suboptimal
loss_constants: null
max_samples: null
max_samples_per_file: 1000
patience: 50
predicates:
- !!python/tuple
  - adjacent
  - 2
- !!python/tuple
  - cell
  - 1
- !!python/tuple
  - package
  - 1
- !!python/tuple
  - locatable
  - 1
- !!python/tuple
  - truck
  - 1
- !!python/tuple
  - at
  - 2
- !!python/tuple
  - empty
  - 1
- !!python/tuple
  - carrying
  - 2
- !!python/tuple
  - adjacent_goal
  - 2
- !!python/tuple
  - cell_goal
  - 1
- !!python/tuple
  - package_goal
  - 1
- !!python/tuple
  - locatable_goal
  - 1
- !!python/tuple
  - truck_goal
  - 1
- !!python/tuple
  - at_goal
  - 2
- !!python/tuple
  - empty_goal
  - 1
- !!python/tuple
  - carrying_goal
  - 2
suboptimal_factor: 2.0
weight_decay: 0.0
