#!/bin/sh

cp -r /home/s8namuel/gnn/gnn-policy-kr22/ .
cd gnn-policy-kr22

python3.10 network/retraining_distillation.py --train data/states/train/gripper/gripper/ --validation data/states/validation/gripper/gripper/ --bugs bugfiles/gripper_iter2/train --logdir /home/s8namuel/gnn/retrain_new_gripper_iter2/no_distillation --policy /home/s8namuel/gnn/gnn-policy-kr22/our_models/gripper_iter2/epoch=84-step=3060-validation_loss=0.009238873608410358.ckpt  --train_indices /home/s8namuel/gnn/gnn-policy-kr22/our_models/gripper_iter2/train_indices_selected_states.json  --val_indices /home/s8namuel/gnn/gnn-policy-kr22/our_models/gripper_iter2/validation_indices_selected_states.json  --domain gripper --seeds 5 --runs 20  --gpus 1 --iterations 2 --no_continue --no_distillation

python3.10 network/retraining_distillation.py --train data/states/train/gripper/gripper/ --validation data/states/validation/gripper/gripper/ --bugs bugfiles/gripper_iter2/train --logdir /home/s8namuel/gnn/retrain_new_gripper_iter2/no_distillation_random_init --policy /home/s8namuel/gnn/gnn-policy-kr22/our_models/gripper_iter2/epoch=84-step=3060-validation_loss=0.009238873608410358.ckpt  --train_indices /home/s8namuel/gnn/gnn-policy-kr22/our_models/gripper_iter2/train_indices_selected_states.json  --val_indices /home/s8namuel/gnn/gnn-policy-kr22/our_models/gripper_iter2/validation_indices_selected_states.json  --domain gripper --seeds 5 --runs 20  --gpus 1 --iterations 2 --no_continue --no_distillation --random_init

python3.10 network/retraining_distillation.py --train data/states/train/gripper/gripper/ --validation data/states/validation/gripper/gripper/ --bugs bugfiles/gripper_iter2/train --logdir /home/s8namuel/gnn/retrain_new_gripper_iter2/distillation --policy /home/s8namuel/gnn/gnn-policy-kr22/our_models/gripper_iter2/epoch=84-step=3060-validation_loss=0.009238873608410358.ckpt  --train_indices /home/s8namuel/gnn/gnn-policy-kr22/our_models/gripper_iter2/train_indices_selected_states.json  --val_indices /home/s8namuel/gnn/gnn-policy-kr22/our_models/gripper_iter2/validation_indices_selected_states.json  --domain gripper --seeds 5 --runs 20  --gpus 1 --iterations 2 --no_continue

python3.10 network/retraining_distillation.py --train data/states/train/gripper/gripper/ --validation data/states/validation/gripper/gripper/ --bugs bugfiles/gripper_iter2/train --logdir /home/s8namuel/gnn/retrain_new_gripper_iter2/distillation_random_init --policy /home/s8namuel/gnn/gnn-policy-kr22/our_models/gripper_iter2/epoch=84-step=3060-validation_loss=0.009238873608410358.ckpt  --train_indices /home/s8namuel/gnn/gnn-policy-kr22/our_models/gripper_iter2/train_indices_selected_states.json  --val_indices /home/s8namuel/gnn/gnn-policy-kr22/our_models/gripper_iter2/validation_indices_selected_states.json  --domain gripper --seeds 5 --runs 20  --gpus 1 --iterations 2 --no_continue --random_init
