#!/bin/sh

cp -r /home/s8namuel/gnn/gnn-policy-kr22/ .
cd gnn-policy-kr22

python3.10 network/retraining_distillation.py --train data/states/train/logistics/ipc2/ipc/ --validation data/states/validation/logistics/ipc2/ipc/ --bugs bugfiles/logistics_split/train --logdir /home/s8namuel/gnn/retrain_new_logistics/no_distillation --policy /home/s8namuel/gnn/gnn-policy-kr22/our_models/logistics_split/epoch=165-step=31208-validation_loss=0.01599125564098358.ckpt --train_indices /home/s8namuel/gnn/gnn-policy-kr22/our_models/logistics_split/train_indices_selected_states.json  --val_indices /home/s8namuel/gnn/gnn-policy-kr22/our_models/logistics_split/validation_indices_selected_states.json  --domain logistics --seeds 5 --runs 20  --gpus 1 --max_samples_per_file 2000 --no_continue --no_distillation

python3.10 network/retraining_distillation.py --train data/states/train/logistics/ipc2/ipc/ --validation data/states/validation/logistics/ipc2/ipc/ --bugs bugfiles/logistics_split/train --logdir /home/s8namuel/gnn/retrain_new_logistics/no_distillation_random_init --policy /home/s8namuel/gnn/gnn-policy-kr22/our_models/logistics_split/epoch=165-step=31208-validation_loss=0.01599125564098358.ckpt --train_indices /home/s8namuel/gnn/gnn-policy-kr22/our_models/logistics_split/train_indices_selected_states.json  --val_indices /home/s8namuel/gnn/gnn-policy-kr22/our_models/logistics_split/validation_indices_selected_states.json  --domain logistics --seeds 5 --runs 20  --gpus 1 --max_samples_per_file 2000 --no_continue --no_distillation --random_init

python3.10 network/retraining_distillation.py --train data/states/train/logistics/ipc2/ipc/ --validation data/states/validation/logistics/ipc2/ipc/ --bugs bugfiles/logistics_split/train --logdir /home/s8namuel/gnn/retrain_new_logistics/distillation --policy /home/s8namuel/gnn/gnn-policy-kr22/our_models/logistics_split/epoch=165-step=31208-validation_loss=0.01599125564098358.ckpt --train_indices /home/s8namuel/gnn/gnn-policy-kr22/our_models/logistics_split/train_indices_selected_states.json  --val_indices /home/s8namuel/gnn/gnn-policy-kr22/our_models/logistics_split/validation_indices_selected_states.json  --domain logistics --seeds 5 --runs 20  --gpus 1 --max_samples_per_file 2000 --no_continue

python3.10 network/retraining_distillation.py --train data/states/train/logistics/ipc2/ipc/ --validation data/states/validation/logistics/ipc2/ipc/ --bugs bugfiles/logistics_split/train --logdir /home/s8namuel/gnn/retrain_new_logistics/distillation_random_init --policy /home/s8namuel/gnn/gnn-policy-kr22/our_models/logistics_split/epoch=165-step=31208-validation_loss=0.01599125564098358.ckpt --train_indices /home/s8namuel/gnn/gnn-policy-kr22/our_models/logistics_split/train_indices_selected_states.json  --val_indices /home/s8namuel/gnn/gnn-policy-kr22/our_models/logistics_split/validation_indices_selected_states.json  --domain logistics --seeds 5 --runs 20  --gpus 1 --max_samples_per_file 2000 --no_continue --random_init

