#!/bin/sh

cp -r /home/s8namuel/gnn/gnn-policy-kr22/ .
cd gnn-policy-kr22

python3.10 network/retraining_distillation.py --train data/states/train/blocks/blocks/ --validation data/states/validation/blocks/blocks/ --bugs bugfiles/blocks/train --logdir /home/s8namuel/gnn/retrain_new_blocks/no_distillation --policy /home/s8namuel/gnn/gnn-policy-kr22/our_models/blocks/epoch=118-step=16779-validation_loss=6.417318218154833e-05.ckpt --train_indices /home/s8namuel/gnn/gnn-policy-kr22/our_models/blocks/train_indices_selected_states.json  --val_indices /home/s8namuel/gnn/gnn-policy-kr22/our_models/blocks/validation_indices_selected_states.json  --domain blocks --seeds 5 --runs 20  --gpus 1 --no_continue --no_distillation

python3.10 network/retraining_distillation.py --train data/states/train/blocks/blocks/ --validation data/states/validation/blocks/blocks/ --bugs bugfiles/blocks/train --logdir /home/s8namuel/gnn/retrain_new_blocks/no_distillation_random_init --policy /home/s8namuel/gnn/gnn-policy-kr22/our_models/blocks/epoch=118-step=16779-validation_loss=6.417318218154833e-05.ckpt --train_indices /home/s8namuel/gnn/gnn-policy-kr22/our_models/blocks/train_indices_selected_states.json  --val_indices /home/s8namuel/gnn/gnn-policy-kr22/our_models/blocks/validation_indices_selected_states.json  --domain blocks --seeds 5 --runs 20  --gpus 1 --no_continue --no_distillation --random_init

python3.10 network/retraining_distillation.py --train data/states/train/blocks/blocks/ --validation data/states/validation/blocks/blocks/ --bugs bugfiles/blocks/train --logdir /home/s8namuel/gnn/retrain_new_blocks/distillation --policy /home/s8namuel/gnn/gnn-policy-kr22/our_models/blocks/epoch=118-step=16779-validation_loss=6.417318218154833e-05.ckpt --train_indices /home/s8namuel/gnn/gnn-policy-kr22/our_models/blocks/train_indices_selected_states.json  --val_indices /home/s8namuel/gnn/gnn-policy-kr22/our_models/blocks/validation_indices_selected_states.json  --domain blocks --seeds 5 --runs 20  --gpus 1 --no_continue

python3.10 network/retraining_distillation.py --train data/states/train/blocks/blocks/ --validation data/states/validation/blocks/blocks/ --bugs bugfiles/blocks/train --logdir /home/s8namuel/gnn/retrain_new_blocks/distillation_random_init --policy /home/s8namuel/gnn/gnn-policy-kr22/our_models/blocks/epoch=118-step=16779-validation_loss=6.417318218154833e-05.ckpt --train_indices /home/s8namuel/gnn/gnn-policy-kr22/our_models/blocks/train_indices_selected_states.json  --val_indices /home/s8namuel/gnn/gnn-policy-kr22/our_models/blocks/validation_indices_selected_states.json  --domain blocks --seeds 5 --runs 20  --gpus 1 --no_continue --random_init
