#!/bin/sh

cp -r /home/s8namuel/gnn/gnn-policy-kr22/ .
cd gnn-policy-kr22

python3.10 network/retraining_distillation.py --train data/states/train/reward2/reward/ --validation data/states/validation/reward2/reward/ --bugs bugfiles/reward_split/train --logdir /home/s8namuel/gnn/retrain_new_reward/no_distillation --policy /home/s8namuel/gnn/gnn-policy-kr22/our_models/reward_split/epoch=139-step=17500-validation_loss=0.011827521957457066.ckpt --train_indices /home/s8namuel/gnn/gnn-policy-kr22/our_models/reward_split/train_indices_selected_states.json  --val_indices /home/s8namuel/gnn/gnn-policy-kr22/our_models/reward_split/validation_indices_selected_states.json  --domain reward --seeds 5 --runs 20  --gpus 1 --max_samples_per_file 2000 --no_continue --no_distillation

python3.10 network/retraining_distillation.py --train data/states/train/reward2/reward/ --validation data/states/validation/reward2/reward/ --bugs bugfiles/reward_split/train --logdir /home/s8namuel/gnn/retrain_new_reward/no_distillation_random_init --policy /home/s8namuel/gnn/gnn-policy-kr22/our_models/reward_split/epoch=139-step=17500-validation_loss=0.011827521957457066.ckpt --train_indices /home/s8namuel/gnn/gnn-policy-kr22/our_models/reward_split/train_indices_selected_states.json  --val_indices /home/s8namuel/gnn/gnn-policy-kr22/our_models/reward_split/validation_indices_selected_states.json  --domain reward --seeds 5 --runs 20  --gpus 1 --max_samples_per_file 2000 --no_continue --no_distillation --random_init

python3.10 network/retraining_distillation.py --train data/states/train/reward2/reward/ --validation data/states/validation/reward2/reward/ --bugs bugfiles/reward_split/train --logdir /home/s8namuel/gnn/retrain_new_reward/distillation --policy /home/s8namuel/gnn/gnn-policy-kr22/our_models/reward_split/epoch=139-step=17500-validation_loss=0.011827521957457066.ckpt --train_indices /home/s8namuel/gnn/gnn-policy-kr22/our_models/reward_split/train_indices_selected_states.json  --val_indices /home/s8namuel/gnn/gnn-policy-kr22/our_models/reward_split/validation_indices_selected_states.json  --domain reward --seeds 5 --runs 20  --gpus 1 --max_samples_per_file 2000 --no_continue

python3.10 network/retraining_distillation.py --train data/states/train/reward2/reward/ --validation data/states/validation/reward2/reward/ --bugs bugfiles/reward_split/train --logdir /home/s8namuel/gnn/retrain_new_reward/distillation_random_init --policy /home/s8namuel/gnn/gnn-policy-kr22/our_models/reward_split/epoch=139-step=17500-validation_loss=0.011827521957457066.ckpt --train_indices /home/s8namuel/gnn/gnn-policy-kr22/our_models/reward_split/train_indices_selected_states.json  --val_indices /home/s8namuel/gnn/gnn-policy-kr22/our_models/reward_split/validation_indices_selected_states.json  --domain reward --seeds 5 --runs 20  --gpus 1 --max_samples_per_file 2000 --no_continue --random_init
