#!/bin/sh

cp -r /home/s8namuel/gnn/gnn-policy-kr22/ .
cd gnn-policy-kr22

python3.10 network/retraining_distillation.py --train data/states/train/visitall2/visitall --validation data/states/validation/visitall2/visitall --bugs bugfiles/visitall_split/train --logdir /home/s8namuel/gnn/retrain_new_visitall/no_distillation --policy /home/s8namuel/gnn/gnn-policy-kr22/our_models/visitall_split/epoch=65-step=1848-validation_loss=0.015052552334964275.ckpt --train_indices /home/s8namuel/gnn/gnn-policy-kr22/our_models/visitall_split/train_indices_selected_states.json  --val_indices /home/s8namuel/gnn/gnn-policy-kr22/our_models/visitall_split/validation_indices_selected_states.json  --domain visitall --seeds 5 --runs 20  --gpus 1 --max_samples_per_file 2000 --no_continue --no_distillation

python3.10 network/retraining_distillation.py --train data/states/train/visitall2/visitall --validation data/states/validation/visitall2/visitall --bugs bugfiles/visitall_split/train --logdir /home/s8namuel/gnn/retrain_new_visitall/no_distillation_random_init --policy /home/s8namuel/gnn/gnn-policy-kr22/our_models/visitall_split/epoch=65-step=1848-validation_loss=0.015052552334964275.ckpt --train_indices /home/s8namuel/gnn/gnn-policy-kr22/our_models/visitall_split/train_indices_selected_states.json  --val_indices /home/s8namuel/gnn/gnn-policy-kr22/our_models/visitall_split/validation_indices_selected_states.json  --domain visitall --seeds 5 --runs 20  --gpus 1 --max_samples_per_file 2000 --no_continue --no_distillation --random_init

python3.10 network/retraining_distillation.py --train data/states/train/visitall2/visitall --validation data/states/validation/visitall2/visitall --bugs bugfiles/visitall_split/train --logdir /home/s8namuel/gnn/retrain_new_visitall/distillation --policy /home/s8namuel/gnn/gnn-policy-kr22/our_models/visitall_split/epoch=65-step=1848-validation_loss=0.015052552334964275.ckpt --train_indices /home/s8namuel/gnn/gnn-policy-kr22/our_models/visitall_split/train_indices_selected_states.json  --val_indices /home/s8namuel/gnn/gnn-policy-kr22/our_models/visitall_split/validation_indices_selected_states.json  --domain visitall --seeds 5 --runs 20  --gpus 1 --max_samples_per_file 2000 --no_continue

python3.10 network/retraining_distillation.py --train data/states/train/visitall2/visitall --validation data/states/validation/visitall2/visitall --bugs bugfiles/visitall_split/train --logdir /home/s8namuel/gnn/retrain_new_visitall/distillation_random_init --policy /home/s8namuel/gnn/gnn-policy-kr22/our_models/visitall_split/epoch=65-step=1848-validation_loss=0.015052552334964275.ckpt --train_indices /home/s8namuel/gnn/gnn-policy-kr22/our_models/visitall_split/train_indices_selected_states.json  --val_indices /home/s8namuel/gnn/gnn-policy-kr22/our_models/visitall_split/validation_indices_selected_states.json  --domain visitall --seeds 5 --runs 20  --gpus 1 --max_samples_per_file 2000 --no_continue --random_init
