universe               = docker
docker_image           = nicolamueller/general_policies:gnn_retraining4
executable             = tune6.sh
output                 = t.$(ClusterId).$(ProcId).out
error                  = t.$(ClusterId).$(ProcId).err
log                    = t.$(ClusterId).log
should_transfer_files  = YES
when_to_transfer_output = ON_EXIT
request_GPUs = 1
request_CPUs = 16
request_memory = 64G
requirements = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted = true
queue 1
